### Avant de lancer le notebook pour la préparation des données, récupérer les données brutes qui sont sur le partage dans le dossier données brutes (les données doit étre sur meme fichier que le notebook)

### les données utilisé ("u10_alesund.csv","v10_alesund.csv", '2m_temperature_alesund.csv', 'surface_solar_radiation_downwards_alesund.csv', 'surface_pressure.csv' )

In [1]:
import pandas as pd 
import numpy as np

# Préparation
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@


La vitesse du vent est donnée par :

$$
 \text{wind} = \sqrt{u_{10}^2 + v_{10}^2} 
$$

In [2]:
df_u = pd.read_csv("u10_alesund.csv")
df_v = pd.read_csv("v10_alesund.csv")

# Assurez-vous qu'ils ont les mêmes lignes (même ordre, date, lat, lon...)
df = df_u.copy()
df["v10"] = df_v["v10"]

# Calcul de la vitesse
df["wind_speed"] = np.sqrt(df["u10"]**2 + df["v10"]**2)

# Sauvegarde
df.to_csv("data_wind_alesund.csv", index=False)




Unité : ms -1

In [ ]:
df_wind_alesund=pd.read_csv('data_wind_alesund.csv')
df_wind_alesund

Unnamed: 0  time           valid_time  latitude  longitude       u10  \
0                8     0  2021-01-01 00:00:00     62.00       6.00 -0.330505   
1                9     0  2021-01-01 00:00:00     62.00       6.25  0.145081   
2                6     0  2021-01-01 00:00:00     62.25       6.00 -2.230896   
3                7     0  2021-01-01 00:00:00     62.25       6.25 -1.430115   
4                4     0  2021-01-01 00:00:00     62.50       6.00 -3.520935   
...            ...   ...                  ...       ...        ...       ...   
384615     1923095     4  2025-05-22 13:00:00     62.50       6.25 -3.932678   
384616     1923092     4  2025-05-22 13:00:00     62.75       6.00 -6.191467   
384617     1923093     4  2025-05-22 13:00:00     62.75       6.25 -5.601623   
384618     1923090     4  2025-05-22 13:00:00     63.00       6.00 -6.256897   
384619     1923091     4  2025-05-22 13:00:00     63.00       6.25 -6.224670   

        number  expver       v10  wind_speed  
0            0     1.0 -1.195236    1.240090  
1            0     1.0 -1.080002    1.089703  
2            0     1.0 -1.651291    2.775547  
3            0     1.0 -1.052658    1.775758  
4            0     1.0 -1.738205    3.926619  
...        ...     ...       ...         ...  
384615       0     5.0 -6.399231    7.511066  
384616       0     5.0 -7.893372   10.031928  
384617       0     5.0 -7.229309    9.145551  
384618       0     5.0 -7.488098    9.758093  
384619       0     5.0 -7.562317    9.794650  

[384620 rows x 10 columns]

In [71]:
df_wind_alesund['longitude'].unique()

array([6.  , 6.25])

on va concerver juste le point  6.25 pour longitude et 62.5 pour latitude qui represente alesund 

In [72]:
df_wind_alesund = df_wind_alesund[
    (df_wind_alesund['longitude'] == 6.25) &
    (df_wind_alesund['latitude'] == 62.5)
]
df_wind_alesund

Unnamed: 0  time           valid_time  latitude  longitude       u10  \
5                5     0  2021-01-01 00:00:00      62.5       6.25 -2.668396   
15              15     0  2021-01-01 01:00:00      62.5       6.25 -2.628647   
25              25     0  2021-01-01 02:00:00      62.5       6.25 -2.359818   
35              35     0  2021-01-01 03:00:00      62.5       6.25 -1.901810   
45              45     0  2021-01-01 04:00:00      62.5       6.25 -1.436829   
...            ...   ...                  ...       ...        ...       ...   
384575     1923055     4  2025-05-22 09:00:00      62.5       6.25 -3.504013   
384585     1923065     4  2025-05-22 10:00:00      62.5       6.25 -3.366760   
384595     1923075     4  2025-05-22 11:00:00      62.5       6.25 -3.384415   
384605     1923085     4  2025-05-22 12:00:00      62.5       6.25 -3.644379   
384615     1923095     4  2025-05-22 13:00:00      62.5       6.25 -3.932678   

        number  expver       v10  wind_speed  
5            0     1.0 -0.841721    2.798005  
15           0     1.0 -0.104568    2.630726  
25           0     1.0  0.361404    2.387332  
35           0     1.0  0.567413    1.984651  
45           0     1.0  0.482239    1.515596  
...        ...     ...       ...         ...  
384575       0     5.0 -6.121231    7.053196  
384585       0     5.0 -5.210800    6.203830  
384595       0     5.0 -5.741196    6.664502  
384605       0     5.0 -6.088974    7.096274  
384615       0     5.0 -6.399231    7.511066  

[38462 rows x 10 columns]

In [73]:
# Garder uniquement les colonnes souhaitées
df_wind_alesund = df_wind_alesund[['valid_time', 'wind_speed']]
df_wind_alesund

valid_time  wind_speed
5       2021-01-01 00:00:00    2.798005
15      2021-01-01 01:00:00    2.630726
25      2021-01-01 02:00:00    2.387332
35      2021-01-01 03:00:00    1.984651
45      2021-01-01 04:00:00    1.515596
...                     ...         ...
384575  2025-05-22 09:00:00    7.053196
384585  2025-05-22 10:00:00    6.203830
384595  2025-05-22 11:00:00    6.664502
384605  2025-05-22 12:00:00    7.096274
384615  2025-05-22 13:00:00    7.511066

[38462 rows x 2 columns]

In [74]:
max_wind = df_wind_alesund['wind_speed'].max()
min_wind = df_wind_alesund['wind_speed'].min()

print("la vitesse du vent maximale (m/s) :", max_wind)
print("la vitesse du vent minimale (m/s) :", min_wind)


la vitesse du vent maximale (m/s) : 18.332586081365644
la vitesse du vent minimale (m/s) : 0.0130898800732579


In [75]:
df_wind_alesund = df_wind_alesund.rename(columns={"valid_time": "Date"})


In [76]:
df_wind_alesund

Date  wind_speed
5       2021-01-01 00:00:00    2.798005
15      2021-01-01 01:00:00    2.630726
25      2021-01-01 02:00:00    2.387332
35      2021-01-01 03:00:00    1.984651
45      2021-01-01 04:00:00    1.515596
...                     ...         ...
384575  2025-05-22 09:00:00    7.053196
384585  2025-05-22 10:00:00    6.203830
384595  2025-05-22 11:00:00    6.664502
384605  2025-05-22 12:00:00    7.096274
384615  2025-05-22 13:00:00    7.511066

[38462 rows x 2 columns]

In [ ]:
df_wind_alesund.to_csv("wind_speed_alesund.csv", index=False)

In [79]:
nan_par_colonne = df_wind_alesund.isna().sum()
print(nan_par_colonne)


Date          0
wind_speed    0
dtype: int64


In [80]:
# Assurez-vous que la colonne est bien en format datetime
df_wind_alesund['Date'] = pd.to_datetime(df_wind_alesund['Date'])

# Calculer la différence entre les lignes
time_diffs = df_wind_alesund['Date'].diff()

# Vérifier si toutes les différences sont exactement de 1 heure
is_one_hour = (time_diffs == pd.Timedelta(hours=1))

# Vérifier s'il y a des valeurs qui ne sont PAS de 1h
if is_one_hour[1:].all():
    print("Toutes les lignes sont espacées d'exactement 1 heure.")
else:
    print("Il y a des lignes qui ne sont pas espacées d'exactement 1 heure.")

Toutes les lignes sont espacées d'exactement 1 heure.


In [ ]:
df_temp_alesund=pd.read_csv('2m_temperature_alesund.csv')
df_temp_alesund

Unnamed: 0  time           valid_time  latitude  longitude        t2m  \
0                0     0  2021-01-01 00:00:00     63.00       6.00  278.54040   
1                1     0  2021-01-01 00:00:00     63.00       6.25  278.28650   
2                2     0  2021-01-01 00:00:00     62.75       6.00  278.49940   
3                3     0  2021-01-01 00:00:00     62.75       6.25  277.45837   
4                4     0  2021-01-01 00:00:00     62.50       6.00  276.17517   
...            ...   ...                  ...       ...        ...        ...   
384855     1924295     4  2025-05-23 13:00:00     62.50       6.25  280.78406   
384856     1924296     4  2025-05-23 13:00:00     62.25       6.00  280.98523   
384857     1924297     4  2025-05-23 13:00:00     62.25       6.25  281.23523   
384858     1924298     4  2025-05-23 13:00:00     62.00       6.00  281.70007   
384859     1924299     4  2025-05-23 13:00:00     62.00       6.25  281.57117   

        number  expver  
0            0     1.0  
1            0     1.0  
2            0     1.0  
3            0     1.0  
4            0     1.0  
...        ...     ...  
384855       0     5.0  
384856       0     5.0  
384857       0     5.0  
384858       0     5.0  
384859       0     5.0  

[384860 rows x 8 columns]

In [4]:
df_temp_alesund = df_temp_alesund[
    (df_temp_alesund['longitude'] == 6.25) &
    (df_temp_alesund['latitude'] == 62.5)
]
df_temp_alesund

Unnamed: 0  time           valid_time  latitude  longitude        t2m  \
5                5     0  2021-01-01 00:00:00      62.5       6.25  274.83923   
15              15     0  2021-01-01 01:00:00      62.5       6.25  274.47168   
25              25     0  2021-01-01 02:00:00      62.5       6.25  274.16553   
35              35     0  2021-01-01 03:00:00      62.5       6.25  273.92847   
45              45     0  2021-01-01 04:00:00      62.5       6.25  273.81543   
...            ...   ...                  ...       ...        ...        ...   
384815     1924255     4  2025-05-23 09:00:00      62.5       6.25  280.28670   
384825     1924265     4  2025-05-23 10:00:00      62.5       6.25  280.44067   
384835     1924275     4  2025-05-23 11:00:00      62.5       6.25  280.56450   
384845     1924285     4  2025-05-23 12:00:00      62.5       6.25  280.62912   
384855     1924295     4  2025-05-23 13:00:00      62.5       6.25  280.78406   

        number  expver  
5            0     1.0  
15           0     1.0  
25           0     1.0  
35           0     1.0  
45           0     1.0  
...        ...     ...  
384815       0     5.0  
384825       0     5.0  
384835       0     5.0  
384845       0     5.0  
384855       0     5.0  

[38486 rows x 8 columns]

In [ ]:
# Garder uniquement les colonnes souhaitées
df_temp_alesund = df_temp_alesund[['valid_time', 't2m']] 
df_temp_alesund

valid_time        t2m
5       2021-01-01 00:00:00  274.83923
15      2021-01-01 01:00:00  274.47168
25      2021-01-01 02:00:00  274.16553
35      2021-01-01 03:00:00  273.92847
45      2021-01-01 04:00:00  273.81543
...                     ...        ...
384815  2025-05-23 09:00:00  280.28670
384825  2025-05-23 10:00:00  280.44067
384835  2025-05-23 11:00:00  280.56450
384845  2025-05-23 12:00:00  280.62912
384855  2025-05-23 13:00:00  280.78406

[38486 rows x 2 columns]

In [6]:
# Conversion en degrés Celsius
df_temp_alesund['t2m_C'] = df_temp_alesund['t2m'] - 273.15
df_temp_alesund = df_temp_alesund.drop(columns="t2m")


C:\Users\emac\AppData\Local\Temp\ipykernel_5316\3397567222.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_temp_alesund['t2m_C'] = df_temp_alesund['t2m'] - 273.15


In [7]:
df_temp_alesund

valid_time    t2m_C
5       2021-01-01 00:00:00  1.68923
15      2021-01-01 01:00:00  1.32168
25      2021-01-01 02:00:00  1.01553
35      2021-01-01 03:00:00  0.77847
45      2021-01-01 04:00:00  0.66543
...                     ...      ...
384815  2025-05-23 09:00:00  7.13670
384825  2025-05-23 10:00:00  7.29067
384835  2025-05-23 11:00:00  7.41450
384845  2025-05-23 12:00:00  7.47912
384855  2025-05-23 13:00:00  7.63406

[38486 rows x 2 columns]

In [8]:
max_temp = df_temp_alesund['t2m_C'].max()
min_temp = df_temp_alesund['t2m_C'].min()

print("Température maximale (°C) :", max_temp)
print("Température minimale (°C) :", min_temp)


Température maximale (°C) : 22.58438000000001
Température minimale (°C) : -9.591219999999964


In [ ]:
df_temp_alesund = df_temp_alesund.rename(columns={"valid_time": "Date"})  # Renommer la colonne pour correspondre à l'autre DataFrame

In [10]:
df_temp_alesund

Date    t2m_C
5       2021-01-01 00:00:00  1.68923
15      2021-01-01 01:00:00  1.32168
25      2021-01-01 02:00:00  1.01553
35      2021-01-01 03:00:00  0.77847
45      2021-01-01 04:00:00  0.66543
...                     ...      ...
384815  2025-05-23 09:00:00  7.13670
384825  2025-05-23 10:00:00  7.29067
384835  2025-05-23 11:00:00  7.41450
384845  2025-05-23 12:00:00  7.47912
384855  2025-05-23 13:00:00  7.63406

[38486 rows x 2 columns]

In [ ]:
df_temp_alesund.to_csv("2m_temp_alesund.csv", index=False) # Sauvegarde du DataFrame

In [12]:
# Assurez-vous que la colonne est bien en format datetime
df_temp_alesund['Date'] = pd.to_datetime(df_temp_alesund['Date'])

# Calculer la différence entre les lignes
time_diffs = df_temp_alesund['Date'].diff()

# Vérifier si toutes les différences sont exactement de 1 heure
is_one_hour = (time_diffs == pd.Timedelta(hours=1))

# Vérifier s'il y a des valeurs qui ne sont PAS de 1h
if is_one_hour[1:].all():
    print("Toutes les lignes sont espacées d'exactement 1 heure.")
else:
    print("Il y a des lignes qui ne sont pas espacées d'exactement 1 heure.")




Toutes les lignes sont espacées d'exactement 1 heure.


In [84]:
nan_par_colonne = df_wind_alesund.isna().sum()
print(nan_par_colonne)

Date          0
wind_speed    0
dtype: int64


$J \, m^{-2}$


In [ ]:
df_rad_alesund=pd.read_csv('surface_solar_radiation_downwards_alesund.csv')
df_rad_alesund

Unnamed: 0  time           valid_time  latitude  longitude       ssrd  \
0                0     0  2021-01-01 00:00:00     63.00       6.00        0.0   
1                1     0  2021-01-01 00:00:00     63.00       6.25        0.0   
2                2     0  2021-01-01 00:00:00     62.75       6.00        0.0   
3                3     0  2021-01-01 00:00:00     62.75       6.25        0.0   
4                4     0  2021-01-01 00:00:00     62.50       6.00        0.0   
...            ...   ...                  ...       ...        ...        ...   
384805     1924045     4  2025-05-23 08:00:00     62.50       6.25  1177216.0   
384806     1924046     4  2025-05-23 08:00:00     62.25       6.00  1184256.0   
384807     1924047     4  2025-05-23 08:00:00     62.25       6.25  1148672.0   
384808     1924048     4  2025-05-23 08:00:00     62.00       6.00  1250304.0   
384809     1924049     4  2025-05-23 08:00:00     62.00       6.25  1209792.0   

        number  expver  
0            0     1.0  
1            0     1.0  
2            0     1.0  
3            0     1.0  
4            0     1.0  
...        ...     ...  
384805       0     5.0  
384806       0     5.0  
384807       0     5.0  
384808       0     5.0  
384809       0     5.0  

[384810 rows x 8 columns]

In [51]:
df_rad_alesund = df_rad_alesund[
    (df_rad_alesund['longitude'] == 6.25) &
    (df_rad_alesund['latitude'] == 62.5)
]
df_rad_alesund

Unnamed: 0  time           valid_time  latitude  longitude       ssrd  \
5                5     0  2021-01-01 00:00:00      62.5       6.25        0.0   
15              15     0  2021-01-01 01:00:00      62.5       6.25        0.0   
25              25     0  2021-01-01 02:00:00      62.5       6.25        0.0   
35              35     0  2021-01-01 03:00:00      62.5       6.25        0.0   
45              45     0  2021-01-01 04:00:00      62.5       6.25        0.0   
...            ...   ...                  ...       ...        ...        ...   
384765     1924005     4  2025-05-23 04:00:00      62.5       6.25   133312.0   
384775     1924015     4  2025-05-23 05:00:00      62.5       6.25   350912.0   
384785     1924025     4  2025-05-23 06:00:00      62.5       6.25   689024.0   
384795     1924035     4  2025-05-23 07:00:00      62.5       6.25   950272.0   
384805     1924045     4  2025-05-23 08:00:00      62.5       6.25  1177216.0   

        number  expver  
5            0     1.0  
15           0     1.0  
25           0     1.0  
35           0     1.0  
45           0     1.0  
...        ...     ...  
384765       0     5.0  
384775       0     5.0  
384785       0     5.0  
384795       0     5.0  
384805       0     5.0  

[38481 rows x 8 columns]

In [52]:
# Garder uniquement les colonnes souhaitées
df_rad_alesund = df_rad_alesund[['valid_time', 'ssrd']]
df_rad_alesund

valid_time       ssrd
5       2021-01-01 00:00:00        0.0
15      2021-01-01 01:00:00        0.0
25      2021-01-01 02:00:00        0.0
35      2021-01-01 03:00:00        0.0
45      2021-01-01 04:00:00        0.0
...                     ...        ...
384765  2025-05-23 04:00:00   133312.0
384775  2025-05-23 05:00:00   350912.0
384785  2025-05-23 06:00:00   689024.0
384795  2025-05-23 07:00:00   950272.0
384805  2025-05-23 08:00:00  1177216.0

[38481 rows x 2 columns]

In [53]:
df_rad_alesund= df_rad_alesund.rename(columns={"valid_time": "Date"})
df_rad_alesund= df_rad_alesund.rename(columns={"ssrd": "radiation_solaire"})

In [81]:
df_rad_alesund

Date  radiation_solaire
5      2021-01-01 00:00:00                0.0
15     2021-01-01 01:00:00                0.0
25     2021-01-01 02:00:00                0.0
35     2021-01-01 03:00:00                0.0
45     2021-01-01 04:00:00                0.0
...                    ...                ...
384765 2025-05-23 04:00:00           133312.0
384775 2025-05-23 05:00:00           350912.0
384785 2025-05-23 06:00:00           689024.0
384795 2025-05-23 07:00:00           950272.0
384805 2025-05-23 08:00:00          1177216.0

[38481 rows x 2 columns]

In [ ]:
df_rad_alesund.to_csv("radiation_alesund.csv", index=False)

In [83]:
nan_par_colonne = df_rad_alesund.isna().sum()
print(nan_par_colonne)

Date                 0
radiation_solaire    0
dtype: int64


In [84]:
# Assurez-vous que la colonne est bien en format datetime
df_rad_alesund['Date'] = pd.to_datetime(df_rad_alesund['Date'])

# Calculer la différence entre les lignes
time_diffs = df_rad_alesund['Date'].diff()

# Vérifier si toutes les différences sont exactement de 1 heure
is_one_hour = (time_diffs == pd.Timedelta(hours=1))

# Vérifier s'il y a des valeurs qui ne sont PAS de 1h
if is_one_hour[1:].all():
    print("Toutes les lignes sont espacées d'exactement 1 heure.")
else:
    print("Il y a des lignes qui ne sont pas espacées d'exactement 1 heure.")

Toutes les lignes sont espacées d'exactement 1 heure.


en Pa

In [ ]:
df_SP_alesund=pd.read_csv('surface_pressure.csv')
df_SP_alesund

Unnamed: 0  time           valid_time  latitude  longitude         sp  \
0                0     0  2021-01-01 00:00:00     63.00       6.00  100588.56   
1                1     0  2021-01-01 00:00:00     63.00       6.25  100655.56   
2                2     0  2021-01-01 00:00:00     62.75       6.00  100801.56   
3                3     0  2021-01-01 00:00:00     62.75       6.25  100350.56   
4                4     0  2021-01-01 00:00:00     62.50       6.00   99503.56   
...            ...   ...                  ...       ...        ...        ...   
384795     1923995     4  2025-05-23 07:00:00     62.50       6.25   99726.56   
384796     1923996     4  2025-05-23 07:00:00     62.25       6.00   98042.56   
384797     1923997     4  2025-05-23 07:00:00     62.25       6.25   96969.56   
384798     1923998     4  2025-05-23 07:00:00     62.00       6.00   96490.56   
384799     1923999     4  2025-05-23 07:00:00     62.00       6.25   95769.56   

        number  expver  
0            0     1.0  
1            0     1.0  
2            0     1.0  
3            0     1.0  
4            0     1.0  
...        ...     ...  
384795       0     5.0  
384796       0     5.0  
384797       0     5.0  
384798       0     5.0  
384799       0     5.0  

[384800 rows x 8 columns]

In [63]:
df_SP_alesund = df_SP_alesund[
    (df_SP_alesund['longitude'] == 6.25) &
    (df_SP_alesund['latitude'] == 62.5)
]
df_SP_alesund

Unnamed: 0  time           valid_time  latitude  longitude         sp  \
5                5     0  2021-01-01 00:00:00      62.5       6.25  98874.560   
15              15     0  2021-01-01 01:00:00      62.5       6.25  98905.060   
25              25     0  2021-01-01 02:00:00      62.5       6.25  98930.625   
35              35     0  2021-01-01 03:00:00      62.5       6.25  98928.000   
45              45     0  2021-01-01 04:00:00      62.5       6.25  98949.560   
...            ...   ...                  ...       ...        ...        ...   
384755     1923955     4  2025-05-23 03:00:00      62.5       6.25  99851.560   
384765     1923965     4  2025-05-23 04:00:00      62.5       6.25  99832.000   
384775     1923975     4  2025-05-23 05:00:00      62.5       6.25  99783.810   
384785     1923985     4  2025-05-23 06:00:00      62.5       6.25  99738.125   
384795     1923995     4  2025-05-23 07:00:00      62.5       6.25  99726.560   

        number  expver  
5            0     1.0  
15           0     1.0  
25           0     1.0  
35           0     1.0  
45           0     1.0  
...        ...     ...  
384755       0     5.0  
384765       0     5.0  
384775       0     5.0  
384785       0     5.0  
384795       0     5.0  

[38480 rows x 8 columns]

In [64]:
# Garder uniquement les colonnes souhaitées
df_SP_alesund = df_SP_alesund[['valid_time', 'sp']]


In [65]:
df_SP_alesund = df_SP_alesund.rename(columns={"valid_time": "Date"})
df_SP_alesund = df_SP_alesund.rename(columns={"sp": "surface_pressure"})

In [85]:
df_SP_alesund

Date  surface_pressure
5      2021-01-01 00:00:00         98874.560
15     2021-01-01 01:00:00         98905.060
25     2021-01-01 02:00:00         98930.625
35     2021-01-01 03:00:00         98928.000
45     2021-01-01 04:00:00         98949.560
...                    ...               ...
384755 2025-05-23 03:00:00         99851.560
384765 2025-05-23 04:00:00         99832.000
384775 2025-05-23 05:00:00         99783.810
384785 2025-05-23 06:00:00         99738.125
384795 2025-05-23 07:00:00         99726.560

[38480 rows x 2 columns]

In [ ]:
df_SP_alesund.to_csv('surface_pressure_alesund.csv', index=False)

In [87]:
nan_par_colonne = df_SP_alesund.isna().sum()
print(nan_par_colonne)

Date                0
surface_pressure    0
dtype: int64


In [88]:
# Assurez-vous que la colonne est bien en format datetime
df_SP_alesund['Date'] = pd.to_datetime(df_SP_alesund['Date'])

# Calculer la différence entre les lignes
time_diffs = df_SP_alesund['Date'].diff()

# Vérifier si toutes les différences sont exactement de 1 heure
is_one_hour = (time_diffs == pd.Timedelta(hours=1))

# Vérifier s'il y a des valeurs qui ne sont PAS de 1h
if is_one_hour[1:].all():
    print("Toutes les lignes sont espacées d'exactement 1 heure.")
else:
    print("Il y a des lignes qui ne sont pas espacées d'exactement 1 heure.")

Toutes les lignes sont espacées d'exactement 1 heure.
